[packages.opentelemetry]
versioned_files = ["crates/opentelemetry/Cargo.toml", { path = "Cargo.toml", dependency = "pyo3-opentelemetry" }, "Cargo.lock"]
changelog = "crates/opentelemetry/CHANGELOG.md"
scopes = ["lib", "opentelemetry", "pyo3-opentelemetry"]

[packages.opentelemetry-macros]
versioned_files = ["crates/opentelemetry-macros/Cargo.toml", { path = "Cargo.toml", dependency = "pyo3-opentelemetry-macros" }, "Cargo.lock"]
changelog = "crates/opentelemetry-macros/CHANGELOG.md"
scopes = ["macros", "opentelemetry-macros", "pyo3-opentelemetry-macros"]

[packages.tracing-subscriber]
versioned_files = ["crates/tracing-subscriber/Cargo.toml", { path = "Cargo.toml", dependency = "pyo3-tracing-subscriber" }, "Cargo.lock"]
changelog = "crates/tracing-subscriber/CHANGELOG.md"
scopes = ["tracing-subscriber", "pyo3-tracing-subscriber"]

[packages.tracing-subscriber-build]
versioned_files = ["crates/tracing-subscriber-build/Cargo.toml", { path = "Cargo.toml", dependency = "pyo3-tracing-subscriber-build" }, "Cargo.lock"]
changelog = "crates/tracing-subscriber-build/CHANGELOG.md"
scopes = ["tracing-subscriber", "pyo3-tracing-subscriber"]

[[workflows]]
name = "release"

[[workflows.steps]]
type = "PrepareRelease"

[[workflows.steps]]
type = "Command"
command = 'git commit -m "chore: prepare release [skip ci]"'

[[workflows.steps]]
type = "Command"
command = "git push"

[[workflows.steps]]
type = "Release"

[github]
owner = "rigetti"
repo = "pyo3-opentelemetry"
