[env]
    # We exclude --no-default-features because pyo3 will not be able to link to python.
    CARGO_HACK_COMMON_FLAGS = "--feature-powerset --optional-deps --exclude-no-default-features"
    CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
    CARGO_MAKE_WORKSPACE_SKIP_MEMBERS = "examples/*"

[tasks.clean]
    clear = true
    script = """
    rm -f *.profraw
    cargo clean
    """

[tasks.install-coverage-tools]
    install_crate = { rustup_component_name = "llvm-tools-preview" }

[tasks.install-cargo-hack]
    install_crate = { crate_name = "cargo-hack", version = "0.5.26" }

[tasks.install-cargo-deny]
    install_crate = { crate_name = "cargo-deny", version = "0.14.2" }

[tasks.install-cargo-deadlinks]
    install_crate = { crate_name = "cargo-deadlinks", version = "0.8.1" }

[tasks.install-cargo-geiger]
    install_crate = { crate_name = "cargo-geiger", version = "0.11.6" }

[tasks.install-cargo-license]
    install_crate = { crate_name = "cargo-license", version= "0.5.1" }

[tasks.install-cargo-msrv]
    install_crate = { crate_name = "cargo-msrv", version = "0.15.1" }

[tasks.install-cargo-outdated]
    install_crate = { crate_name = "cargo-outdated", version = "0.13.1" }

[tasks.install-grcov]
    install_crate = { crate_name = "grcov", version = "v0.8.19" }

[tasks.install-gitlab-clippy]
    install_crate = { crate_name = "gitlab_clippy", version = "1.0.3" }

[tasks.install-cargo-nextest]
    install_crate = { crate_name = "cargo-nextest", version = "0.9.57" }

[tasks.check]
    clear = true
    dependencies = ["install-cargo-hack"]
    script = "cargo hack check $CARGO_HACK_COMMON_FLAGS --all-targets"

[tasks.clippy-fix]
    clear = true
    dependencies = ["install-clippy-any", "install-cargo-hack"]
    script = "cargo hack clippy $CARGO_HACK_COMMON_FLAGS --all-targets --fix"

[tasks.clippy]
    clear = true
    dependencies = ["install-clippy-any", "install-cargo-hack"]
    script = "cargo hack clippy $CARGO_HACK_COMMON_FLAGS --all-targets"

[tasks.clippy-ci]
    dependencies = ["install-clippy-any", "install-cargo-hack", "install-gitlab-clippy"]
    script = "cargo hack clippy $CARGO_HACK_COMMON_FLAGS --all-targets --message-format=json | gitlab-clippy > gl-code-quality-report.json"

[tasks.coverage-tests]
    dependencies = ["install-coverage-tools", "install-cargo-hack"]
    script = "cargo hack test $CARGO_HACK_COMMON_FLAGS"

[tasks.coverage-tests.env]
    RUSTFLAGS = "-Cinstrument-coverage"
    LLVM_PROFILE_FILE = ".coverage/coverage-%p-%m.profraw"

[tasks.coverage-base]
    dependencies = ["install-grcov", "coverage-tests"]
    command = "grcov"
    args = [
        ".",
        "-s", ".",
        "--keep-only", "**/src/**", # Ignore files not in a src/ folder
        "-p", "src",
        "--binary-path", "./target/debug/",
        "--ignore", "./tests",
        "--ignore", "/*", # Ignore dependencies, whose source are in absolute path $HOME/.cargo/...
        "-t", "${COVERAGE_OUTPUT_TYPE}",
        "--branch",
        "--llvm",
        "--ignore-not-existing",
        "-o", "${COVERAGE_OUTPUT_FILE}"
    ]

[tasks.coverage-ci]
    run_task = "coverage-base"
[tasks.coverage-ci.env]
    COVERAGE_OUTPUT_TYPE = "cobertura"
    COVERAGE_OUTPUT_FILE = "./target/debug/cobertura.xml"

[tasks.coverage-html]
    run_task = "coverage-base"
[tasks.coverage-html.env]
    COVERAGE_OUTPUT_TYPE = "html"
    COVERAGE_OUTPUT_FILE = "./target/debug/coverage/"

[tasks.view-coverage]
    linux_alias = "view-coverage-linux"
    mac_alias = "view-coverage-macos"
    windows_alias = "view-coverage-windows"

[tasks.view-coverage-linux]
    dependencies = ["coverage-html"]
    command = "xdg-open"
    args = ["./target/debug/coverage/index.html"]

[tasks.view-coverage-macos]
    dependencies = ["coverage-html"]
    command = "open"
    args = ["./target/debug/coverage/index.html"]

[tasks.view-coverage-windows]
    dependencies = ["coverage-html"]
    command = "cmd.exe"
    args = ["/c", "start", "./target/debug/coverage/index.html"]

[tasks.deadlinks]
    dependencies = ["install-cargo-deadlinks"]
    command = "cargo"
    # we removed "--check-intra-doc-links" due to flaky and opaque failures such
    # as https://github.com/rigetti/pyo3-opentelemetry/actions/runs/6723277856/job/18273013287?pr=7.
    args = ["deadlinks", "--check-http", "--ignore-fragments"]

[tasks.deny]
    workspace = false
    dependencies = ["install-cargo-deny"]
    command = "cargo"
    args = ["deny", "check", "-c", "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/deny.toml", "all"]

[tasks.deny-advisories]
    workspace = false
    dependencies = ["install-cargo-deny"]
    command = "cargo"
    args = ["deny", "check", "-c", "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/deny.toml", "advisories"]

[tasks.deny-ban]
    workspace = false
    dependencies = ["install-cargo-deny"]
    command = "cargo"
    args = ["deny", "check", "-c", "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/deny.toml", "ban"]

[tasks.deny-bans]
    workspace = false
    dependencies = ["install-cargo-deny"] 
    command = "cargo"
    args = ["deny", "check", "-c", "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/deny.toml", "bans"]

[tasks.deny-license]
    workspace = false
    dependencies = ["install-cargo-deny"]
    command = "cargo"
    args = ["deny", "check", "-c", "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/deny.toml", "license"]

[tasks.deny-licenses]
    dependencies = ["install-cargo-deny"]
    command = "cargo"
    args = ["deny", "check", "-c", "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/deny.toml", "licenses"]

[tasks.deny-sources]
    workspace = false
    dependencies = ["install-cargo-deny"]
    command = "cargo"
    args = ["deny", "check", "-c", "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/deny.toml", "sources"]

[tasks.geiger]
    dependencies = ["install-cargo-geiger"]
    command = "cargo"
    args = ["geiger"]

[tasks.license]
    dependencies = ["install-cargo-license"]
    command = "cargo"
    args = ["license", "--all-features", "--avoid-dev-deps"]

[tasks.msrv]
    dependencies = ["install-cargo-msrv"]
    command = "cargo"
    args = ["msrv"]

[tasks.msrv-verify]
    dependencies = ["install-cargo-msrv"]
    command = "cargo"
    args = ["msrv", "verify"]

[tasks.outdated]
    dependencies = ["install-cargo-outdated"]
    command = "cargo"
    args = ["outdated"]

[tasks.nextest]
    dependencies = ["install-cargo-hack", "install-cargo-nextest"]
    script = "cargo hack nextest run $CARGO_HACK_COMMON_FLAGS"

[tasks.examples]
    dependencies = ["example-lib-python"]

# Reintroduce cargo deny upon resolution of https://github.com/rigetti/pyo3-opentelemetry/issues/16
[tasks.check-all]
    dependencies = ["check", "clippy", "deadlinks", "msrv-verify", "nextest"]

[tasks.pre-ci-flow]
    dependencies = ["check", "clippy", "deadlinks", "msrv-verify"]

