from typing import Dict, Optional

class PyO3OpenTelemetryCarrier:
    def __init__(self) -> None: ...
    def __setitem__(self, key: str, value: str) -> None: ...

def example_function(*, extractor: Optional[PyO3OpenTelemetryCarrier] = None) -> Dict[str, str]: ...
async def example_function_async(*, extractor: Optional[PyO3OpenTelemetryCarrier] = None) -> Dict[str, str]: ...

class ExampleStruct:
    def __init__(self) -> None: ...
    def example_method(self, extractor: Optional[PyO3OpenTelemetryCarrier] = None) -> Dict[str, str]: ...
    async def example_method_async(self, extractor: Optional[PyO3OpenTelemetryCarrier] = None) -> Dict[str, str]: ...
