[tasks.python-install-dependencies]
  private = true
  script = "poetry install"

[tasks.python-build]
  dependencies = ["python-install-dependencies"]
  script = '''
  poetry run maturin develop
  poetry run black .
  poetry run ruff . --fix
  '''
    
[tasks.python-format]
  dependencies = []
  script = '''
  poetry run black .
  poetry run ruff . --fix
  '''

[tasks.python-check]
  dependencies = ["python-build"]
  script = '''
  poetry run black . --check
  poetry run ruff .
  poetry run pyright .
  poetry run stubtest --allowlist .stubtest-allowlist --allowlist pyo3_opentelemetry_lib/_tracing_subscriber/.stubtest-allowlist --mypy-config-file ./mypy.ini pyo3_opentelemetry_lib
  '''

[tasks.python-test]
  dependencies = ["python-build"]
  script = '''
  mkdir -p pyo3_opentelemetry_lib/test/__artifacts__
  poetry run pytest .

  # Note, the follow are all tests that initialize a global tracing subscriber, which is only possible to do
  # once per process. The alternative here would be to use `pytest-xdist` in order to run each test in a
  # separate process; that proved non-trivial on a first attempt, as the tests ran into sevaral unexpected
  # failures.

  poetry run pytest 'pyo3_opentelemetry_lib/test/tracing_test.py::test_file_export[02]' --with-global-tracing-configuration
  poetry run pytest 'pyo3_opentelemetry_lib/test/tracing_test.py::test_file_export[03]' --with-global-tracing-configuration
  poetry run pytest 'pyo3_opentelemetry_lib/test/tracing_test.py::test_file_export_asynchronous[00]' --with-global-tracing-configuration

  poetry run pytest 'pyo3_opentelemetry_lib/test/tracing_test.py::test_otlp_export[02]' --with-global-tracing-configuration
  poetry run pytest 'pyo3_opentelemetry_lib/test/tracing_test.py::test_otlp_export[03]' --with-global-tracing-configuration
  poetry run pytest 'pyo3_opentelemetry_lib/test/tracing_test.py::test_otlp_export_asynchronous[00]' --with-global-tracing-configuration
  poetry run pytest 'pyo3_opentelemetry_lib/test/tracing_test.py::test_otlp_export_asynchronous[01]' --with-global-tracing-configuration
  '''

[tasks.python-check-all]
  dependencies = ["python-check", "python-test"]

