# *****************************************************************************
# *                             AUTO-GENERATED CODE                           *
# *                                                                           *
# * This code was generated by the `pyo3-tracing-subscriber` crate. Any       *
# * modifications to this file should be made to the script or the generation *
# * process that produced this code. Specifically, see:                       *
# * `pyo3_tracing_subscriber::stubs::write_stub_files`                        *
# *                                                                           *
# * Do not manually edit this file, as your changes may be overwritten the    *
# * next time the code is generated.                                          *
# *****************************************************************************

from typing import Union

from .file import Config as FileConfig
from .otel_otlp import Config as OtlpConfig
from .otel_otlp_file import Config as OtlpFileConfig

Config = Union[
    FileConfig,
    OtlpFileConfig,
    OtlpConfig,
]
"""
One of the supported layer configurations that may be set on the subscriber configuration.
"""
