# Based on https://github.com/actions-rs/meta/blob/master/recipes/msrv.md

on: 
  push:
    branches: [main]
  pull_request: {}

name: Cargo Deny 

jobs:
  deny:
    name: Cargo Deny
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          # the scripts seem to inevitably involve building something that requires a newer version
          # of rust, so we just run against stable for now.
          # - 1.60.0
    steps:
      # Checkout, setup Rust tools, etc.
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      - uses: Swatinem/rust-cache@v2
      - run: curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
      - name: Install cargo-make
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --debug cargo-make
      - name: Run Cargo Deny
        continue-on-error: true
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: --makefile Makefile.toml deny

