name: Publish

on:
  workflow_dispatch:

jobs:
  cargo-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: Swatinem/rust-cache@v2
      - run: cargo publish --workspace --locked --token ${{ secrets.CRATES_IO_TOKEN }}
