name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:
    # "Manually publish release"
    inputs:
      opentelemetry:
        description: "Publish pyo3-opentelemetry"
        type: boolean
        default: false
      opentelemetry_macros:
        description: "Publish pyo3-opentelemetry-macros"
        type: boolean
        default: false
      tracing_subscriber:
        description: "Publish pyo3-tracing-subscriber"
        type: boolean
        default: false

jobs:
  cargo-publish:
    runs-on: ubuntu-latest
    if: |
      ${{ (github.event_name == 'release')
       || (github.event_name == 'workflow_dispatch') }}
    steps:
      - uses: actions/checkout@v5
      - uses: Swatinem/rust-cache@v2
      - run: cargo publish --workspace --locked --token ${{ secrets.CRATES_IO_TOKEN }}
